baseURL = "http://souvikhaldar.info"
languageCode = "en-us"
title = "Souvik Haldar"
theme = "hugo-coder"
paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Souvik Haldar"
  favicon = "fav.png"
  info = "Using Feynman Technique to understand things I covet"
  description = "Backend Engineer | Creator | Explorer"
  avatarurl = "/images/IMG_20180912_145153_434.jpg"
  #footercontent = "getting better each day, everyday"
  dateformat = "January 2,2006"
  rtl = false

  # Use inverted colors
  inverted = false
  # Series see also post count
  maxSeeAlsoItems = 5

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/souvikhaldar"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/s0uvikhaldar"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/souvikhaldar/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@souvikhaldar"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook"
    weight = 6
    url = "https://www.facebook.com/s0uvikhaldar"



[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about"

        [[languages.en.menu.main]]
        name = "Articles"
        weight = 2
        url = "/articles/"

        [[languages.en.menu.main]]
        name = "Events"
        weight = 3
        url = "/events/"

        [[languages.en.menu.main]]
        name = "Programming"
        weight = 4
        url = "/programming/"

        [[languages.en.menu.main]]
        name = "Networking"
        weight = 5
        url = "/networking/"

        [[languages.en.menu.main]]
        name = "Photography"
        weight = 6
        url = "https://www.instagram.com/theperfectbehold/"  

        [[languages.en.menu.main]]
        name = "Presentations"
        weight = 5
        url = "/presentations/"

        [[languages.en.menu.main]]
        name = "OS"
        weight = 5
        url = "/OS/"



