baseURL = "https://www.souvikhaldar.info"
description = "Ramblings of an aspiring coder"
languageCode = "en-us"
title = "Souvik Haldar"
theme = "hugo-coder"

[params]
  favicon = "fav.png"
  facebook = "https://www.facebook.com/s0uvikhaldar"
  twitter = "https://twitter.com/s0ouvikhaldar"
  instagram = "https://www.instagram.com/souvikhaldar/"
  youtube = ""
  github = "https://github.com/souvikhaldar"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/souvikhaldar/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sikkim.jpg"
  recent_posts_number = 3

[menu]

  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = -110

  [[menu.main]]
    name = "Articles"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/articles/"
    weight = -100
  [[menu.main]]
    name = "Events"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/events/"
    weight = -100

  [[menu.main]]
    name = "Books"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/books/"
    weight = -100

  [[menu.main]]
    name = "Programming"
    post = "<span class='alert'>New!</span>"
    pre = "<i class='fa fa-road'></i>"
    url = "/programming/"
    weight = -100

  [[menu.main]]
    name = "Photography"
    url = "https://www.instagram.com/theperfectbehold/"
    
