baseURL = "https://www.souvikhaldar.info"
languageCode = "en-us"
title = "Souvik Haldar"
theme = "ananke"
[params]
  favicon = "https://img.icons8.com/ios-glyphs/30/000000/gamma.png"
  description = "Ramblings of an aspiring coder"
  facebook = "https://www.facebook.com/s0uvikhaldar"
  twitter = "https://twitter.com/s0ouvikhaldar"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/souvikhaldar/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  featured_image = "/images/sikkim.jpg"
