baseURL = "https://www.souvikhaldar.info"
description = "Ramblings of an aspiring coder"
languageCode = "en-us"
title = "Souvik Haldar"
theme = "ananke"
[params]
  favicon = "fav.png"
  disqusShortname = "https-www-souvikhaldar-info"
  facebook = "https://www.facebook.com/s0uvikhaldar"
  twitter = "https://twitter.com/s0ouvikhaldar"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/souvikhaldar/"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/sikkim.jpg"
